import { OMBDBResponse } from "@/modules/OMDBApi";

// This is a sample of movies from the OMBDB API...
// In the future, we shall fetch this from an API based on user preferences
export const CONTENT_SAMPLE: Readonly<OMBDBResponse[]> = [
  {
    Title: "City of God",
    Year: "2002",
    Rated: "R",
    Released: "13 Feb 2004",
    Runtime: "130 min",
    Genre: "Crime, Drama",
    Director: "Fernando Meirelles, Kátia Lund",
    Writer: "Paulo Lins, Bráulio Mantovani",
    Actors: "Alexandre Rodrigues, Leandro Firmino, Matheus Nachtergaele",
    Plot: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    Language: "Portuguese",
    Country: "Brazil, France, Germany",
    Awards: "Nominated for 4 Oscars. 75 wins & 50 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMGU5OWEwZDItNmNkMC00NzZmLTk1YTctNzVhZTJjM2NlZTVmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.6/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "79/100",
      },
    ],
    Metascore: "79",
    imdbRating: "8.6",
    imdbVotes: "791,969",
    imdbID: "tt0317248",
    Type: "movie",
    DVD: "17 Dec 2015",
    BoxOffice: "$7,564,459",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Parasite",
    Year: "2019",
    Rated: "R",
    Released: "08 Nov 2019",
    Runtime: "132 min",
    Genre: "Drama, Thriller",
    Director: "Bong Joon Ho",
    Writer: "Bong Joon Ho, Han Jin-won",
    Actors: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
    Plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    Language: "Korean, English",
    Country: "South Korea",
    Awards: "Won 4 Oscars. 306 wins & 264 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "99%",
      },
      {
        Source: "Metacritic",
        Value: "96/100",
      },
    ],
    Metascore: "96",
    imdbRating: "8.5",
    imdbVotes: "918,211",
    imdbID: "tt6751668",
    Type: "movie",
    DVD: "11 Oct 2019",
    BoxOffice: "$53,369,749",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Whiplash",
    Year: "2014",
    Rated: "R",
    Released: "15 Oct 2014",
    Runtime: "106 min",
    Genre: "Drama, Music",
    Director: "Damien Chazelle",
    Writer: "Damien Chazelle",
    Actors: "Miles Teller, J.K. Simmons, Melissa Benoist",
    Plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    Language: "English",
    Country: "United States",
    Awards: "Won 3 Oscars. 98 wins & 144 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "89/100",
      },
    ],
    Metascore: "89",
    imdbRating: "8.5",
    imdbVotes: "961,236",
    imdbID: "tt2582802",
    Type: "movie",
    DVD: "08 Sep 2016",
    BoxOffice: "$13,092,000",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Good Will Hunting",
    Year: "1997",
    Rated: "R",
    Released: "09 Jan 1998",
    Runtime: "126 min",
    Genre: "Drama, Romance",
    Director: "Gus Van Sant",
    Writer: "Matt Damon, Ben Affleck",
    Actors: "Robin Williams, Matt Damon, Ben Affleck",
    Plot: "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
    Language: "English",
    Country: "United States",
    Awards: "Won 2 Oscars. 24 wins & 61 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "97%",
      },
      {
        Source: "Metacritic",
        Value: "70/100",
      },
    ],
    Metascore: "70",
    imdbRating: "8.3",
    imdbVotes: "1,042,254",
    imdbID: "tt0119217",
    Type: "movie",
    DVD: "14 Apr 2016",
    BoxOffice: "$138,433,435",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "The Shawshank Redemption",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "142 min",
    Genre: "Drama",
    Director: "Frank Darabont",
    Writer: "Stephen King, Frank Darabont",
    Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    Plot: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 7 Oscars. 21 wins & 42 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "82/100",
      },
    ],
    Metascore: "82",
    imdbRating: "9.3",
    imdbVotes: "2,851,631",
    imdbID: "tt0111161",
    Type: "movie",
    DVD: "15 Aug 2008",
    BoxOffice: "$28,767,189",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "The Invisible Guest",
    Year: "2016",
    Rated: "TV-MA",
    Released: "06 Jan 2017",
    Runtime: "106 min",
    Genre: "Crime, Drama, Mystery",
    Director: "Oriol Paulo",
    Writer: "Oriol Paulo, Lara Sendim",
    Actors: "Mario Casas, Ana Wagener, Jose Coronado",
    Plot: "A successful entrepreneur accused of murder and a witness preparation expert have less than three hours to come up with an impregnable defense.",
    Language: "Spanish, English",
    Country: "Spain",
    Awards: "2 wins & 3 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTEwYTkzMTMtODEzNC00YWM2LTgxNDMtZWNkNTQzNDVjMWQ2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMDY4NTQ1MA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "70%",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "189,966",
    imdbID: "tt4857264",
    Type: "movie",
    DVD: "09 Jul 2017",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Shutter Island",
    Year: "2010",
    Rated: "R",
    Released: "19 Feb 2010",
    Runtime: "138 min",
    Genre: "Mystery, Thriller",
    Director: "Martin Scorsese",
    Writer: "Laeta Kalogridis, Dennis Lehane",
    Actors: "Leonardo DiCaprio, Emily Mortimer, Mark Ruffalo",
    Plot: "Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient, where Teddy uncovers a shocking truth about the place.",
    Language: "English, German",
    Country: "United States",
    Awards: "11 wins & 66 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.2/10" },
      { Source: "Rotten Tomatoes", Value: "69%" },
      { Source: "Metacritic", Value: "63/100" },
    ],
    Metascore: "63",
    imdbRating: "8.2",
    imdbVotes: "1,431,168",
    imdbID: "tt1130884",
    Type: "movie",
    DVD: "01 Aug 2013",
    BoxOffice: "$128,012,934",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Joker",
    Year: "2019",
    Rated: "R",
    Released: "04 Oct 2019",
    Runtime: "122 min",
    Genre: "Crime, Drama, Thriller",
    Director: "Todd Phillips",
    Writer: "Todd Phillips, Scott Silver, Bob Kane",
    Actors: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
    Plot: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    Language: "English, German",
    Country: "United States, Canada, Australia",
    Awards: "Won 2 Oscars. 121 wins & 245 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.4/10" },
      { Source: "Rotten Tomatoes", Value: "69%" },
      { Source: "Metacritic", Value: "59/100" },
    ],
    Metascore: "59",
    imdbRating: "8.4",
    imdbVotes: "1,450,964",
    imdbID: "tt7286456",
    Type: "movie",
    DVD: "03 Oct 2019",
    BoxOffice: "$335,477,657",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Hateful Eight",
    Year: "2015",
    Rated: "R",
    Released: "30 Dec 2015",
    Runtime: "168 min",
    Genre: "Crime, Drama, Mystery",
    Director: "Quentin Tarantino",
    Writer: "Quentin Tarantino",
    Actors: "Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh",
    Plot: "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
    Language: "English, Spanish, French, Persian",
    Country: "United States",
    Awards: "Won 1 Oscar. 45 wins & 116 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.8/10" },
      { Source: "Rotten Tomatoes", Value: "75%" },
      { Source: "Metacritic", Value: "68/100" },
    ],
    Metascore: "68",
    imdbRating: "7.8",
    imdbVotes: "650,792",
    imdbID: "tt3460252",
    Type: "movie",
    DVD: "02 Mar 2017",
    BoxOffice: "$54,117,416",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Silence of the Lambs",
    Year: "1991",
    Rated: "R",
    Released: "14 Feb 1991",
    Runtime: "118 min",
    Genre: "Crime, Drama, Thriller",
    Director: "Jonathan Demme",
    Writer: "Thomas Harris, Ted Tally",
    Actors: "Jodie Foster, Anthony Hopkins, Scott Glenn",
    Plot: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    Language: "English, Latin",
    Country: "United States",
    Awards: "Won 5 Oscars. 70 wins & 50 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.6/10" },
      { Source: "Rotten Tomatoes", Value: "95%" },
      { Source: "Metacritic", Value: "86/100" },
    ],
    Metascore: "86",
    imdbRating: "8.6",
    imdbVotes: "1,521,422",
    imdbID: "tt0102926",
    Type: "movie",
    DVD: "27 Aug 2015",
    BoxOffice: "$130,742,922",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Green Book",
    Year: "2018",
    Rated: "PG-13",
    Released: "16 Nov 2018",
    Runtime: "130 min",
    Genre: "Biography, Comedy, Drama",
    Director: "Peter Farrelly",
    Writer: "Nick Vallelonga, Brian Hayes Currie, Peter Farrelly",
    Actors: "Viggo Mortensen, Mahershala Ali, Linda Cardellini",
    Plot: "A working-class Italian-American bouncer becomes the driver for an African-American classical pianist on a tour of venues through the 1960s American South.",
    Language: "English, Italian, Russian, German",
    Country: "United States, China",
    Awards: "Won 3 Oscars. 58 wins & 123 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYzIzYmJlYTYtNGNiYy00N2EwLTk4ZjItMGYyZTJiOTVkM2RlXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.2/10" },
      { Source: "Rotten Tomatoes", Value: "77%" },
      { Source: "Metacritic", Value: "69/100" },
    ],
    Metascore: "69",
    imdbRating: "8.2",
    imdbVotes: "550,051",
    imdbID: "tt6966692",
    Type: "movie",
    DVD: "19 Feb 2019",
    BoxOffice: "$85,080,171",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 162 wins & 164 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "84/100" },
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,821,976",
    imdbID: "tt0468569",
    Type: "movie",
    DVD: "14 Jun 2010",
    BoxOffice: "$534,987,076",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "A Clockwork Orange",
    Year: "1971",
    Rated: "X",
    Released: "02 Feb 1972",
    Runtime: "136 min",
    Genre: "Crime, Sci-Fi",
    Director: "Stanley Kubrick",
    Writer: "Stanley Kubrick, Anthony Burgess",
    Actors: "Malcolm McDowell, Patrick Magee, Michael Bates",
    Plot: "In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn't go as planned.",
    Language: "English",
    Country: "United Kingdom, United States",
    Awards: "Nominated for 4 Oscars. 12 wins & 25 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.3/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "77/100" },
    ],
    Metascore: "77",
    imdbRating: "8.3",
    imdbVotes: "870,120",
    imdbID: "tt0066921",
    Type: "movie",
    DVD: "15 Aug 2008",
    BoxOffice: "$26,617,553",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Memento",
    Year: "2000",
    Rated: "R",
    Released: "25 May 2001",
    Runtime: "113 min",
    Genre: "Mystery, Thriller",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan, Jonathan Nolan",
    Actors: "Guy Pearce, Carrie-Anne Moss, Joe Pantoliano",
    Plot: "A man with short-term memory loss attempts to track down his wife's murderer.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 2 Oscars. 57 wins & 59 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.4/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "83/100" },
    ],
    Metascore: "83",
    imdbRating: "8.4",
    imdbVotes: "1,304,023",
    imdbID: "tt0209144",
    Type: "movie",
    DVD: "01 Mar 2017",
    BoxOffice: "$25,544,867",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Elite Squad",
    Year: "2007",
    Rated: "R",
    Released: "12 Oct 2007",
    Runtime: "115 min",
    Genre: "Action, Crime, Drama",
    Director: "José Padilha",
    Writer: "José Padilha, Rodrigo Pimentel, Bráulio Mantovani",
    Actors: "Wagner Moura, André Ramiro, Caio Junqueira",
    Plot: "In 1997 Rio de Janeiro, Captain Nascimento has to find a substitute for his position while trying to take down drug dealers and criminals before the Pope visits.",
    Language:
      "Portuguese, Greek, Latin, French, English, German, Italian, Spanish",
    Country: "Brazil, United States, Argentina",
    Awards: "47 wins & 16 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMGJjN2M1ZGMtNjg3ZC00MTA1LWEyZDItMjIzZTRlYzgzODRkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.0/10" },
      { Source: "Rotten Tomatoes", Value: "51%" },
      { Source: "Metacritic", Value: "33/100" },
    ],
    Metascore: "33",
    imdbRating: "8.0",
    imdbVotes: "108,869",
    imdbID: "tt0861739",
    Type: "movie",
    DVD: "10 Mar 2017",
    BoxOffice: "$8,744",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
